# Study Description {#intro}

## Background

Cancer patients undergoing chemotherapy can experience short and long term effects such as fatigue and decreased exercise tolerance (\\TODO reference). We theorize that cytotoxic chemotherapy causes long-term damage to mitochondria over the whole body, which results in less efficient and effective oxygen use and therefore fatigue. 

Previous attempts to measure muscle mitochondrial function have included muscle biopsies and MRI. Muscle biopsies are invasive procedures that most investigators do not want to put their patients through. For MRI measurements, patients must remain very still. Even for functional MRI, the type of movement is very limited due to the amount of space within the MRI. This constrains the measurements of mitochondrial function to rest or low intensity exercise such as calf raises, that cannot measure the body's response to systemic cardiorespiratory exercise.

With the advancements in Near Infrared Spectroscopy (NIRS) in recent years, the oxygenation of large muscles such as the vastus lasteralis can be measured during exercises like running and cycling.  

## Purpose

This study aims to measure muscle mitchondrial oxidative capacity throughout chemotherapy for patients with primary non-metastatic breast or gynecological cancers. 

