# IRB {#IRB}

## IRBNet {#IRBNet}

Prisma Health uses IRBNet to manage the IRB status of research projects. 

Students who wish to participate in this research study must have an IRBNet account. In their IRBNet profile, they must have a certificate of the CITI Training for **Biomedical/Clinical Course GCP Social and Behavior Research Best Practices for Clinical Research** and an Investigator Assurance Form uploaded. 

For new students to be able to interact with patients and administer testing, we have to submit an IRB amendment with their names in it. We cannot submit an IRB amendment until they have an IRBNet account with those files uploaded and submitted.  Without the IRB amendment, students can only shadow or observe. An amendment can take a few days to be approved so all of the following steps must be completed as soon as possible. 

### Create an IRBNet Account {#CreateIRBNetAccount}

1. Go to https://www.irbnet.org.
2. Click `New User Registration` in the top right corner under the Log In. 
3. Fill out your first and last name and choose a username and password.
    - Always use your proper name with standard capitalization.
    - Passwords must be at least 8 characters. 4. Accept the terms and conditions.
5. Search for your organization. 
    - Medical students search for the University of South Carolina. 
    - Furman students search for Furman University. 
6. Select your organization and click `Continue`.
7. Input your contact information using the email associated with your organization. 
8. Click `Register` to continue.  
    - If you mistyped your email, click the `edit` button next to the email field
9. Click `Continue`. An activation email will be sent to you. 
10. Open the email from IRBNet and click on the activation link. 

#### CITI Training {#CITITraining}

Some students may have already completed the necessary CITI training. If that is the case, ensure you have the certificate for the completed courses and skip the next steps. 

1. Log into the CITI website at https://www.citiprogram.org – sign in using a USER ID and password (one you already have or if needed – created one).
2. Affiliate yourself with your organization – medical students will choose the University of South Carolina and Furman students will choose Furman University.  You will answer a few questions. (Question 1; (A) 2; (Not at this time); 3; (No) 4; (GCP – Social and Behavioral Research Best Practices for Clinical Research); 5;(Not Require) 6;(Not at this time) 7;(Not at this time) 8; (Select None)
After answering these questions, you will arrive at a screen where you will choose which module to take, and you will choose the Biomedical/Clinical Course or GCP Social and Behavior Research Best Practices for Clinical Research. What will happen next is that any courses you previously have taken, through CITI, should populate if they are the same as what we require. Any courses that need to be completed will show up as a live link. You will only need to take those courses and not retake what you have already done.

#### Upload files into IRBNet {#IRBNetCertificates}

1. Log into IRBNet. 
2. Under `Manage your User Profile`, under `Training & Credentials`, click `Add New Record`. 
3. In the `Document Type` field, select `My CITI Training`.
4. Under `Effective Date`, put the date on the certificate. 
5. In the `File:` field, clicke `Browse` and select the file for your CITI Training certificate. 
6. Click `Attach`.
7. Under `Manage your User Profile`, under `Training & Credentials`, click `Add New Record`. 
8. In the `Document Type` field, select ``.
9. Under `Effective Date`, put the date you signed the Investigator Assurance Form. 
10. In the `File` field, click `Browse` and select the file for your *signed* investigator assueance form. 
11. Click `Attach`.
12. Both files should be listed under `Training & Credentials`.
13. Under `Training & Credentials` click `submit`. 
14. When it prompts you to select a committee to submit to, select **Prisma IRB Subcommittee C**. 
    

## Protocol{#IRB-Protocol}

### Participants{#Appendix-IRB-Protocol-Participants}

Participants recruited for this study will be breast cancer or gynecological cancer patients (N=40) who agree to participate in an exercise study examining the effects of chemotherapy on muscle mitochondrial oxidative capacity, a measure of skeletal muscle health.  A written informed consent will be obtained from the participants before data collection.  This study has been submitted for review by the Institutional Review Board at the Prisma Office of Research Compliance and Administration (ORCA).  We pledge to abide by all applicable institutional and governmental regulations regarding the ethical use of human volunteers for the duration of this research.

This study focuses on breast cancer or gynecological cancer patients who will undergo a standard of care chemotherapy treatment as directed by their oncologist. 
Other eligibility requirements for this study are as follows: 

- Patients diagnosed with breast cancer or gynecological cancer without distance metastasis
- Ages > 20 years old 
- Able to perform exercise on a stationary cycle ergometer at moderate intensities for a maximum of 15 minutes
- Hemoglobin values greater than 10 at baseline
- ALT and AST values less than 2.5X the upper limit of normal by institutional standards
- Godin-Shepard Leisuretime Physical Activity Questionnaire (GLTEQ) score of 14 or greater will be included. A score of less than 14 is considered insufficiency active/sedentary.

The exclusion criteria include patients with: 

- Clinically advanced cardiovascular disease
- Clinically advanced pulmonary disease
- Disease requiring continuous oxygen supplementation
- Greater than 2 centimeters or more of subcutaneous adipose tissue on the anterior thigh
- Inability to walk or stand
- Movement disorders
- Spinal cord injuries
- Autoimmune disorders
- Pregnant or breastfeeding
- Mini-Mental State Examination (MMSE)

Participants for this study will be recruited through informative pamphlets at the Center for Integrative Oncology Survivorship, Prisma Health System’s Cancer Institute at Greenville Memorial Hospital and affiliated physician offices. 

### Experimental Design {#Appendix-IRB-Protocol-ExperimentalDesign}

We will use an observational, 2-way, treatment x time, within-subjects research design to compare skeletal muscle oxidative capacity of the vastus lateralis muscle, during stationary cycling, across breast cancer or gynecological cancer patients at baseline and across their chemotherapy regimen. Muscle mitochondrial oxidative capacity of the Vastus Lateralis muscle will be non-invasively evaluated using continuous wave, Near Infrared Resonance Spectroscopy (NIRS, PortaMon by Artinis Medical Systems BV in The Netherlands). 

### Study protocol {#Appendix-IRB-Protocol-StudyProtocol}

The NIRS participant testing will be performed in the University of South Carolina School of Medicine Greenville’s Human Performance Laboratory located within Cancer Institute Faris Road facility. Testing will take approximately 30 minutes per session, with a maximum of 180 minutes of participation per patient. The independent variables in this study are drug regimen and number of chemotherapy treatments. The dependent variables in this study will be the change in oxygenation and deoxygenation status of the vastus lateralis as measured by the NIRS device, indicative of mitochondrial oxidative capacity, after a bout of cycling. Patients will be asked to avoid exercise and use of certain substances (tobacco, alcohol, caffeine, and contraindicated medications) 24 hours prior to testing.

The NIRS device consists of three LED transmitters that transmit light waves into muscle tissue and one high sensitivity PIN diode receiver, equipped with ambient light protection, which assesses light received from the transmitters.  The three transmitters each emit light at two wavelengths. These wavelengths correspond to the absorption wavelengths of oxyhemoglobin (O2Hb) and deoxyhemoglobin in the skeletal muscle tissue (approximately 760 nm and 850 nm). These wavelengths of light will be received from three separate transmitter distances (30mm, 35mm, and 40mm) at 10 Hz.  The ΔO2Hb and Δ tissue saturation index (TSI%) will be calculated as the change from the last 30-s average of the work interval to the last 30-s average of the recovery interval. Oxygen uptake (VO2) will be obtained by using open-circuit spirometry (Parvo Medics, Inc, Salt Lake City, Utah). Cycling power will be determined via lactate threshold curves generated for each participant. 
Participants will be asked to perform exercise in shorts or equivalent. Participants will first sit at rest in a chair, as the NIRS device is applied to the vastus lateralis. The device will have double sided adhesive tape to lightly secure its position to the skin. The device will be wrapped in a black cloth to fully secure its position, limit device mobility, and block ambient light in the laboratory. Participants will then stand and walk to the cycle with the NIRS secured to the participant’s leg. Participants will sit on the bike for a 2-minute rest while wearing a fitted mask that comfortably measures the participant’s rate and amount of oxygen uptake (VO2) and other ventilatory measurements at rest and during exercise.  

#### Visit 1 {#Appendix-IRB-Protocol-StudyProtocol-Visit1}

Researchers will determine the participant’s lactate threshold curve and ventilatory threshold during a graded exercise test (Table 1). The lactate threshold is a measure of the rate at which capillary blood lactate measurements rise as an effect of increased exercise intensity. The blood lactate curve will be used to determine an individualized power wattage for subsequent exercise testing of “on-off kinetics” (see below description). Capillary blood lactate levels will be obtained by finger stick for point of care testing. Ventilatory threshold will be measured using indirect calorimetry via a metabolic cart that captures expired gasses (O2 and CO2) through a comfortable silicone mask worn by the participant. 

A baseline blood lactate level will be obtained at rest, then the participant will be instructed to cycle for three minutes beginning at 10W. After the 3-minute stage is complete, the power output will increase by 15 watts. The participant will cycle for 3 minutes at each stage until their lactate threshold reaches 4.0 mmol/L. Once the blood lactate reaches 4.0 mmol/L, one final, three-minute stage will be performed. A final lactate reading will be obtained at the completion of this exercise stage. The power output that is equivalent to 1.1x the wattage at which their lactate threshold exceeded 4.0 mmol/L will be used as the exercise intensity (“on-kinetics”) for subsequent visits accompanying chemotherapy treatments.

#### Subsequent Visits {#Appendix-IRB-Protocol-StudyProtocol-SubsequentVisits}

Participants will return for each subsequent visit within a week before their next chemotherapy infusion as long as they are able to safely continue the exercise protocol (Table 2). The NIRS device will be secured to the participant’s leg similar to the first visit and the participants will put on the mask to measure ventilation. Participants will begin pedaling for a warmup at 0 watts for 2 minutes. After the two-minute warm up period is completed, the power output will increase to the previously calculated wattage of 1.1x LT. The participant will cycle at a self-selected cadence at this power wattage for a duration of 2 minutes (“on-kinetics”). At the end of each on-kinetics stage, participants will be asked to rate their level of effort during exercise, Rate of Perceived Exertion (RPE). The participant will then stop pedaling and will remain in recovery, sitting on the bike for 2 minutes (“off-kinetics” stage). With 5 seconds remaining in the “off-kinetics” stage, the participant will start pedaling at the same self-selected cadence for their next “on-kinetics” stage, followed by another 2-min “off-kinetics” period. This cycle of exercise followed by rest, known as on-off kinetics, will repeat for a total maximum of 3 times, or until the participant reaches volitional fatigue.

#### Collection of Surveys and Biometrics at Each Visit {#Appendix-IRB-Protocol-StudyProtocol-Surveys}

We will be administering MoCA, BFI, Physical Activity Intake, PROMIS Global Health, and GLTPAQ surveys prior to participant engagement in cycling exercises.  We will also be administering BFI, PROMIS Global Health, and Physical Activity Follow-up surveys after each individual study session to assess changes in cancer related fatigue associated with chemotherapy treatment that may develop throughout the study time period. 

Patients will undergo routine, standard of care blood draws for a CBC and metabolic testing per their managing physician with an additional tube, during the same venipuncture, for a study covered aliquot for biomarkers related to mitochondrial health for correlative research.

For biomarker analysis, exosomes from patient serum (approximately 250 uL samples) will be isolated using an ExoQuick ULTRA EV Isolation System (System Biosciences). Exosomes will then be detected with Western blotting with exosome specific antibodies. Exosome samples will be sent for RNASeq analysis of RNA within the isolated exosomes at System Biosciences. Bioinformatics analysis of the RNAs identified from the RNASeq will then be used to determine if there are specific RNAs present in patient blood associated with changes in mitochondrial function. In addition, selected mRNAs associated with mitochondrial function will be assessed (expression levels determined) with RT-qPCR using aliquots of the isolated serum exosomes.

### Statistical Analyses {#Appendix-IRB-Protocol-StatisticalAnalyses}
 
ANOVA one way with tukey post-hoc analysis to detect differences between drug regimen groups at each time point (baseline, all subsequent chemotherapy treatments) for time constant response and change in mitochondrial function for mitochondrial oxidative capacity. One-way ANOVAs will be used to additionally detect differences between different timepoints from baseline to final chemotherapy treatment for each individual chemotherapy regimen. 

