# Surveys {#Appendix-Surveys}

## Brief Fatigue Inventory {#Appendix-Surveys-bfi}

The Brief Fatigue Inventory (BFI) is a 9 item survey designed to assess fatigue severity in cancer patients [@mendoza1999]. Each item is measured on a 0-10 numeric scale. The final score is the mean of the 9 measure items and can range from 0-10. A score can be calculated if at least 5 items out of 9 are answered by taking the mean of the completed items. 

## Godin Leisure-Time Exercise Questionnaire {#Appendix-Surveys-glteq}

Godin and Shephard made the `Leisure Time Exercise Questionnaire` (LTEQ) in 1985 [@godinshepherd85]. The LTEQ was originally a two item survey: “Item 1 consists of 3 parts, in which participants note how often per week they do strenuous, moderate, and mild exercise. Item 2 asks participants to note how often they engage in an activity long enough to work up a sweat.“  This was used to group people into several different categories of activity levels. 
 
In 2011, Godin published the `Godin-Shephard Leisure Time Physical Activity Questionnaire` (GLTPAQ) [@godinshepherd11]. This removed the second item and was used to group respondents into 2 categories, “insufficiently active” and “active” based on the ACSM guidelines for weekly moderate and strenuous physical activity levels. 
 
The form that we use says `Godin-Leisure Time Exercise Questionnaire` across the top of the form, by the Oncology Nursing Society. At the bottom left, it says ‘adapted from: Godin, G. (2011). The Godin-Shephard leisure-time physical activity questionnaire. Health & Fitness Journal of Canada, 4(1), 18-22.’  I don’t know why that’s the title they chose to put on the top of the form, it’s made things more confusing than it needs to be. I have so far been unable to find the original paper that uses this form. 

## Mini-Mental State Examination {#Appendix-Surveys-mmse}

The Mini-Mental State Examination is a cognitive screening tool. We use it to screen for cognitive impairment before patients can participate in this study. Patients must score greater than 27 to continue with the study. 

## Physical Activity History {#Appendix-Surveys-pah}

The Physical Activity History is intended to capture the physical activity history of the respondent using the FITVVP principles. 

There are two physical activity history forms: Intake and Follow Up. 

The Physical Activity History: Intake form asks the patient to describe their normal physical activities. It consists of 5 items. Item 1 asks if the respondent participates in moderate to vigorous physical activity. If the respondent answers yes, there are spaces to describe the physical activity below. Item 2 asks the respondent if this describes their physical activity from the past 5 years. If not, the respondent can describe how their physical activity habits have changed over the past 5 years. Item 3 asks if the respondent participates in interval training. If the respondent answers yes, there are spaces to describe the training. Items 4 and 5 ask about participation in recreational sports and whether the respondent has had any injuries that would contradict participation in exercise. 

The Physical Activity History: FollowUp asks the respondent to describe their physical activities since the last time they answered the Physical Activity History survey. This form does not ask about physical history prior to the most recent visit visit. 

## PROMIS Global Health v1.1  {#Appendix-Surveys-promis}

We use the PROMIS Global Health v1.1 form. This is a discontinued PROMIS measure. Follow the scoring guidelines to convert the v1.1 questions and answers into v1.2. The scoring guidelines have been uploaded into the RedCap file repository and the RedCap instrument follows those guidelines. 


