# Data Storage {#DataStorage}

Follow all appropriate data export instructions for PARVO and NIRS data.

All physical copies are stored in a locked filing cabinet in the Human Performance Lab.

The study [RedCap][RedCapURL] stores all identifying patient information and digital copies of data.

After a patient is identified and signs a consent form for the study, the research coordinator will fill out the `New Patient` survey in RedCap. When this survey is completed, it automatically assigns a study ID number to the patient and sends an email to Frankie Bennett and Sara Biddle about the newly consented participant. 

When a patient completes an HPL visit, go to the patient's record in RedCap.

## Missing Data Codes {#DataStorage-MissingData}

The following missing data codes are enabled in RedCap:

- INV, Invalid
- NA, Not Applicable
- OTH, Other
- NI, No Information

When inputting data into RedCap, use the following guidelines to determine which missing data code to use. You can input a missing data code by selecting the `M` next to the input field. 

If the item is blank, as in not answered or no one wrote it down on the data collection sheet, use `NI, No Information`. If the item had an error during data collection, for example if the lactate meter shows `ERR`, use `INV, Invalid`. If the item was not used during data collection, use `NA, Not Applicable`. If the reason does not fit into any of the above categories, use `OTH, Other` and record a comment by clicking on the text bubble icon and typing into the notes field. 

### Patient Information

After consenting the new patient, open up the patient's chart in Epic and fill out the forms under `Patient Information`. 



### Lactate Threshold Visit

Under the `Lactate Threshold` event in the appropriate patient record in RedCap, start filling out the data collection instruments for the event. 




Fill out the following data collection instruments: `HPL Visit`, `One-Time Measurements`, `Lactate Parvo`, `Godin Leisuretime Exercise Questionnaire`, `Mini-Mental State Examination`, `Brief Fatigue Inventory`, `PROMIS SF v1.1-Global Health`, `Physical Activity`, and `Data Files`. 

The information to fill out `HPL Visit`, `One-Time Measurements`, and `Lactate Parvo` will be found on the `Lactate Threshold Data Collection Sheet` that was filled out during the patient visit. 

 





[RedCapURL]:https://redcap.prismahealth.org
