# Exercise Testing {#ExerciseTesting}

There are two types of exercise tests. 

The lactate threshold test is conducted to determine what power output (wattage) is associated with a rise in lactate production. For the general population, lactate threshold is considered to be 4.0 mMoL/L. 

The On/Off Kinetics test is conducted to measure the patient's mitochondrial oxidative capacity. The transition from work to rest allows the NIRS device to capture the magnitude and rate of oxygen recovery after exercise. The power output of the exercise is 110% of the power output at lactate threshold. We use this power output in order to ensure that the exercise is difficult enough to produce a change in oxygen levels during exercise. 

We split up the work of administering the exercise test into three jobs: RPE, Parvo, and NIRS. 

For lactate threshold testing, the person doing RPE is the person taking the lactate measurements. For On/Off Kinetics testing, the person in charge of RPE tends to be the person who is in contact with the patient the most. With thirty seconds left in every stage of testing (both lactate threshold testing and on/off kinetics testing), they will hold up the clipboard with the RPE scale and say the following: *"What is the first number that comes to mind?"*. **Say those exact words.**  The patient will then say or point to the number that corresponds to how they are feeling. This person is also in charge of watching the patient on the bike and checking in to see how they feel. If the exercise becomes too difficult or the patient does not feel well, they are in charge of communicating with the rest of the team to end the test early and get the patient off the bike. 

The person in charge of NIRS watches the NIRS computer as it is collecting data. They take note of any times when the signal from the NIRS is corrupted or when the patient is moving around during a rest. Record the time on the NIRS computer and note what was going on, i.e. if the DAQ for Tx3 was red or if the patient was moving. During the on/off kinetics test, this person also helps the patient put their foot on the box. The NIRS device is always placed on the right leg, so the left leg of the patient goes on the box. The left leg needs to go on the box during a rest section to help the patient stay perfectly still. If both feet are left in the stirrups of the bike, the patient will tend to rock their feet back and forth to stay balanced on the bike. This causes movement in the NIRS data that we do not want. We choose to put the left leg on the box rather than the right leg because if the right leg is placed on the box like that, then the patient will be tensing their right quadriceps muscles. This would mean that we are not getting a true rest measurement of the vastus lateralis. Therefore, we put the left foot on a box and allow the right leg to dangle at complete rest in the stirrups of the bike. With fifteen seconds left in a work section before a rest, kneel down by the box and get ready. The Parvo person will give you a countdown to the end of the stage and when it hits 0 and the patient stops pedaling, pull their left foot out of the stirrup and place their heel on the box. Remind the patient to stay completely still. During a rest period, they are more likely to want to talk to fill the silence and if you make them laugh too hard, the NIRS data will be effected. Try to keep them still and focused on the resting. This is especially true for the last rest section, as they are done with the exercise which is the "hard part". 

The person in charge of the Parvo has the most work to do.

- Check data validity
    Check during the inital rest on the bike that the Parvo is collecting valid data. At rest, VO2 should be between 3-5. If VO2 is lower than 3, check that the mask is forming a good seal around the patient's face. If the seal is good and the VO2 is still below 3, ask the patient to sit up straight and take normal breaths. Some people hunch over on the bike which decreases the volume of air that they breath in and out. Some people hold their breath a little bit when you put the mask on because it can feel a little claustrophobic. Remind them that the mask is not limiting their breathing, it is just measuring what they are breathing. Tell them that the system we use is the same one they use at NASA and the Olympic Training Centers. This tends to help people feel better.
    The Parvo shows the RPM of the bike. If the RPM drops below 60, encourage the patient to get the RPM back up above 60. If the RPM are higher than 110, remind the patient that they do not need to work that hard and try to drop the RPM below 90. 
- Recording data during the test
    For each stage, record the VO_2_, Heart Rate (bpm), and RPE. For a lactate threshold test, record the lactate measurements when the person taking the lactates yells them out. The VO2 and Heart Rate will be on the Parvo screen. There is a real time heart rate number and a fifteen second average number. The real time number is smaller and will be blinking in time with the heart rate. The fifteen second average number will be in one of the blue boxes in the top left. The fifteen second average numbers refresh every fifteen seconds. If the stage is three minutes long, you will wait until two minutes and fourty five seconds of the stage have passed and the final refresh has happened for that stage to record the VO2 and heart rate. 
- Communicating timing
    For each stage, they should tell the patient when a stage is starting, when they are halfway done with the stage, when there is 30 seconds left in a stage, and give a countdown to the next stage. This would result in the following statements during one stage: "The stage has begun. You are halfway done with this stage. Thirty seconds left in this stage. Ten. Nine. Eight. Seven. Six. Five. Four. Three. Two. One." If this is a lactate threshold test, you can make a comment about how this next stage should be slightly more difficult or how they should feel a change in the wattage. If this is an on/off kinetics test, they can tell the patient what the next stage will be, i.e. work or rest. During a work stage, this could sound something like: "Two minutes of exercise starting now. You're halfway to a rest. Thirty seconds left until rest." All of these statements also help the other staff to do their jobs. The thirty second mark tells the RPE person to get an RPE measurement and the countdown allows the NIRS person to get ready to do the box. 
    There are two places to look for the time on the Parvo. There is a total elapsed time and there is a time left in this stage. The time left in the stage is the easiest to look at for keeping track of timing. 

## Lactate Threshold Exercise Test {#ExerciseTesting-LT}

### Specifications {#ExerciseTesting-LT-Specs}

The lactate threshold test is completed on a cycle ergometer. 

Ventilatory measurements are collected breath by breath via metabolic cart. 
Lactate is measured via finger prick.

Prior to beginning exercise testing, measure resting blood lactate. This should be less than 2.0 mmoL/L in order to begin testing. Normal resting blood lactate lies between 0.8-1.2 mmoL/L, however stress or nervousness prior to an exercise test can increase resting blood lactate levels. If lactate levels are slightly elevated but still lower than 2.0 mmol/L, then lactate may drop back down as the body uses lactate during warm up stages. 

The exercise test is conducted as follows:

Begin with a two minute rest. The subject sits on the stationary bike without pedaling for two minutes. 
Each subsequent stage is three minutes in duration. The wattage increases by a consistent amount between each stage. During the last 30 seconds of each stage, blood lactate is measured via finger prick. Each lactate measurement is taken in pairs for duplicability.

Lactate will increase as exercise difficulty increases. When the subject's blood lactate exceeds 4.0 mmol/L, have the subject finish the next stage and then end the test. If the subject feels they cannot complete the next stage, end the test immediately. A blood lactate of 4.0 mmol/L should roughly correspond to a moderately difficult exercise intensity but should not be a maximal effort. 

### Selecting Wattage Jumps {#ExerciseTesting-LT-Watts}

Discuss the subject's physical activity levels. If the subject doesn't participate in much cardiorespiratory fitness activities, then start at a very low wattage (10 Watts) and make modest jumps (15 Watts).  If the subject participates in long distance running, cycling, or swimming, then the subject may start at a higher wattage than less fit subjects and/or make larger jumps. 

When selecting wattage jumps, remember that lactate should increase exponentially as wattage increases linearly. Also, when conducting testing, there is no second chance to get the testing correct. It is better to use a very low starting wattage with modest increases as the initial settings, because if the subject is fitter than expected and their blood lactate levels remain stagnant, the wattage jumps can be increased during testing. Blood lactate will not go down in the time it takes to conduct the testing, and if the difficulty increases too quickly then the blood lactate levels will increase so quickly that it will be difficult to analyze the lactate curve. 

## On/Off Kinetics Exercise Test {#ExerciseTesting-Onoff}

### Specifications {#ExerciseTesting-Onoff-Specs}

The on/off kinetics test is completed on a cycle ergometer. 

Ventilatory measurements are collected breath by breath via metabolic cart (ParvoMedics OneTrue 2400, \@ref(Parvo)). Muscle oxygenation measurements are collected via SR-NIRS (Artinis Medical Systems PortaMon, \@ref(PortaMon))

The exercise test consists of three square-wave transitions from exercise at 110% of wattage at lactate threshold to rest. Each stage of the test is two minutes long.

|Time|Intensity||
|----|---------|-|
|0-2|Baseline Rest| |
|2-4|Warm Up (0 Watts)| |
|4-6|Exercise|Transition|
|6-8|Rest|1|
|8-10|Exercise|Transition|
|10-12|Rest|2|
|12-14|Exercise|Transition|
|14-16|Rest|3|

