--- 
title: "NIRS Study Information"
author: "Sara Biddle"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: saragracebiddle/Nirs-Study-Info
description: "This contains all current information about the NIRS Study."
---

# Study Description {#intro}

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

## Background

Cancer patients undergoing chemotherapy can experience short and long term effects such as fatigue and decreased exercise tolerance (\\TODO reference). We theorize that cytotoxic chemotherapy causes long-term damage to mitochondria over the whole body, which results in less efficient and effective oxygen use and therefore fatigue. 

Previous attempts to measure muscle mitochondrial function have included muscle biopsies and MRI. Muscle biopsies are invasive procedures that most investigators do not want to put their patients through. For MRI measurements, patients must remain very still. Even for functional MRI, the type of movement is very limited due to the amount of space within the MRI. This constrains the measurements of mitochondrial function to rest or low intensity exercise such as calf raises, that cannot measure the body's response to systemic cardiorespiratory exercise.

With the advancements in Near Infrared Spectroscopy (NIRS) in recent years, the oxygenation of large muscles such as the vastus lateralis can be measured during exercises like running and cycling.  

NIRS measurements have been extensively written about in correlation with VO_2 measurements within the last decade. 

In this study, we utilize square-wave transition testing to examine the efficiency of oxygen use in the muscle during whole body cardiorespiratory exercise. Square-wave transition exercise tests consist of repeated transitions from lower intensity exercise to higher intensity exercise. These transitions require the body to quickly use and replace oxygen levels. The speed and magnitude of these oxygen changes relate to how well the mitochondria can pull oxygen from the blood and utilize it to create ATP. We expect that people with healthier mitochondria to extract and use more oxygen and with greater speed than people with less healthy mitochondria. 

## Purpose

This study aims to measure muscle mitochondrial oxidative capacity throughout chemotherapy for patients with primary non-metastatic breast or gynecological cancers. 


