# Methods {#Methods}

## Lactate Threshold Protocol {#Methods-LT}

This protocol is the participant's first visit. 


### Preparation {#Methods-LT-prep}

At least 30 minutes prior to when the participant is scheduled to arrive, turn on the metabolic cart. 

Print out the following instruments:

- MoCA \@ref(Appendix-Surveys-moca)
- MMSE \@ref(Appendix-Surveys-mmse)
- Godin-Leisure Time Exercise Questionnaire \@ref(Appendix-Surveys-glteq)
- Physical Activity History \@ref(Appendix-Surveys-pah)
- BFI \@ref(Appendix-Surveys-bfi)
- PROMIS Global Health \@ref(Appendix-Surveys-promis)
- Lactate Threshold Data Collection Sheet

Write the patient's study ID number, visit ID, and the date in the upper left corner of each in pen. 

Assemble the VO~2~ mask except for the blue rubber part as described in \@ref(Parvo-MaskAssembly). 

Prepare the PortaMon as described in \@ref(PortaMon-Preparation). 

Calibrate the metabolic cart as described in \@ref(Parvo-Calibration).

### Data Collection {#Methods-LT-DataCollection}

Use the steps described in \@ref(Appendix-Instruments-Ultrasound-Usage) to measure the participant's subcutaneous adipose tissue thickness above their vastus lateralis.

After the patient arrives, the participant's subcutaneous adipose tissue thickness is measured using an ultrasound. If ATT is less than 2 centimeters, the participant continues through the next steps.

Place the NIRS device over the area measured using ultrasound following the steps described in  \@ref(PortaMon-Placement).

Administer the following instruments:

- MoCA \@ref(Appendix-Surveys-moca)
- MMSE \@ref(Appendix-Surveys-mmse)
- Godin-Leisure Time Exercise Questionnaire \@ref(Appendix-Surveys-glteq)

The MoCA, MMSE, and GLTEQ are exclusion criteria. If the participant does not pass these items, they cannot proceed with the study, therefore they are administered before other instruments. If the participant passes the exclusion instruments, proceed with the rest of the instruments. These instruments are not filled out by the participant- a study staff member must administer and score these instruments. 

Have the subject complete the following instruments:

- Physical Activity History \@ref(Appendix-Surveys-pah)
- BFI \@ref(Appendix-Surveys-bfi)
- PROMIS Global Health \@ref(Appendix-Surveys-promis)

These instruments are completed by the participant. 

Review the completed Godin-Leisure Time Exercise Questionnaire and Physical Activity History instruments. Use your best judgement in collaboration with the other investigators to determine the wattage jumps. See \@ref(ExerciseTesting-LT-Watts) for further information about deciding wattage jumps.

Measure the subject's face to determine mask size. Record mask size on data collection sheet. Finish assembling mask.

Put the heart rate monitor on the patient.

Have the subject get on the stationary bike and make adjustments to the seat height, seat depth, pedal length, and handlebar placement to the comfort of the participant. 

If the PortaMon has been on for at least 10 minutes, proceed. 

Place the assembled mask on the participant's face and connect clear tubing to the mask.

Conduct Lactate Threshold Exercise Test as described in \@ref(ExerciseTesting-LT). 


## On/Off Kinetics Protocol {#Methods-Onoff}

Use the steps described in \@ref(PortaMon) and \@ref(PortaMon-Placement) along with the reference image of the previous placement to place the device in the same location as the last visit. 

Have the subject complete the following instruments:

- Physical Activity History \@ref(Appendix-Surveys-pah)
- BFI \@ref(Appendix-Surveys-bfi)
- PROMIS Global Health \@ref(Appendix-Surveys-promis)

If the PortaMon has been on for at least 10 minutes, proceed.

Place the assembled mask on the participant's face and connect clear tubing to the mask.

Conduct On/Off Kinetics Exercise Test as described in \@ref(ExerciseTesting-Onoff).

Take the mask off the patient's face. Help the patient get off the bike. Remove the NIRS device and the heart rate monitor.


